# Root logger option
rootLogger=INFO, STDOUT, LOGFILE

# Define console appender
appender.console=org.apache.log4j.ConsoleAppender
appender.console.name = STDOUT
appender.console.type = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%-5level] %msg%n

# Define rolling file appender
appender.file.type = File
appender.file.name = LOGFILE
appender.file.fileName = logs/FileUpload.log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n
appender.file.filter.threshold.type = ThresholdFilter
appender.file.filter.threshold.level = info